# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
timezone: US/Pacific

# Site settings
title: The Natural Order of Things
email: thimoteus@teknik.io
description: > # this means to ignore newlines until "baseurl:"
  The natural order of things is just the usual ordering on the natural numbers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thimoteus.github.io" # the base hostname & protocol for your site
github_username: thimoteus

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
